language: php
php: 
  - '7.0'
  - '7.1'
  - '7.2'

install: composer install --dev --no-suggest

script: composer run tests

after_success: 
  - bash <(curl -s https://codecov.io/bash) -t a3a391f9-6223-4b92-92ec-b3bd7ce0593e